### ISSUE TITLE
Choose between Selenium Puppeteer or Playwright

### ISSUE THREAD

**Issue by tbolwerk** [tbolwerk/capita-selecta#1]

**Comment by tbolwerk** [comment]
Playwright does not support Linux OS

**Comment by tbolwerk** [comment]
We go with playwright, since we expect everyone to go with Selenium

**Comment by User-TGK** [comment]
https://www.browserstack.com/guide/cypress-vs-selenium-vs-playwright-vs-puppeteer

**Comment by TimMaasGeesteranus** [comment]
Most difficult task of the whole project is done ✅
