### ISSUE TITLE
Crawler must be able to accept cookies (or data processing) on GDPR consent dialogs

### ISSUE THREAD

**Issue by tbolwerk** [tbolwerk/capita-selecta#9]

**Comment by User-TGK** [comment]
Currently not working:

youtube.com _(alles accepteren)_
google-analytics.com _(ok)_
 doubleclick.net _(ok)_



https://debbie.codes/blog/how-to-locate-elements-in-playwright/
https://playwright.dev/docs/other-locators
https://docs.apify.com/sdk/js/docs/2.3/typedefs/playwright-crawler-options
